name       : python-beniget
version    : 0.4.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/b/beniget/beniget-0.4.1.tar.gz : 75554b3b8ad0553ce2f607627dad3d95c60c441189875b98e097528f8e23ac0c
homepage   : https://github.com/serge-sans-paille/beniget/
license    : BSD 3-Clause
component  : programming.python
summary    : Extract semantic information about static Python code
description: |
    Beniget is a collection of Compile-time analyse on Python Abstract Syntax Tree(AST). It's a building block to write static analyzer or compiler for Python.
builddeps  :
    - python-gast  # check
rundeps    :
    - python-gast
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
